### ISSUE TITLE
Fix position of 'Read more' button

### ISSUE THREAD

**Issue by 128-95** [kittycash/blog#12]
Mobile view:

![screen shot 2018-03-25 at 14 50 11](https://user-images.githubusercontent.com/34062064/37875181-f09e2f14-303b-11e8-9e71-d0c58da93cce.png)

**Comment by 128-95** [comment]
The title of the blogpost should be clickable as well to read the article.

**Comment by 128-95** [comment]
Position 'Read more' button is fixed by https://github.com/kittycash/kittycash.com/pull/36

**Comment by bradkendall** [comment]
Fixed in PR #14
