### ISSUE TITLE
Fix positioning spacing of website parts

### ISSUE THREAD

**Issue by jdknives** [kittycash/blog#15]
![bildschirmfoto 2018-03-28 um 20 34 06](https://user-images.githubusercontent.com/36450093/38049071-7abbb08a-32c7-11e8-83b5-22ee6bb47f58.png)
![bildschirmfoto 2018-03-28 um 20 34 20](https://user-images.githubusercontent.com/36450093/38049072-7ae1c9d2-32c7-11e8-96ac-6a746aeeb054.png)

- [x] Make sure the game is aligned with the left end of the play button.

- [x] makes sure the logo is not shifted to the centre of the screen

- [ ] make sure the telegram link is not colliding with the design curve

**Comment by 128-95** [comment]
https://github.com/kittycash/kittycash.com/pull/41
